### ISSUE TITLE
Transaction not found if send with big palyload (749 byte)

### ISSUE THREAD

**Issue by pyoner** [MinterTeam/minter-explorer-web#2]
For example see:
https://testnet.explorer.minter.network/transactions/Mtba6709cc5227d20dcf9450a41300e69033f55141

But node api shows that the transaction exists:
https://minter-node-1.testnet.minter.network/api/transaction/Mtba6709cc5227d20dcf9450a41300e69033f55141

**Comment by daniildulin** [comment]
fixed
