### ISSUE TITLE
Incorrect balance after check activation

### ISSUE THREAD

**Issue by i7495** [MinterTeam/minter-explorer-web#4]
Steps to reproduce:
1) Issue check on the wallet 1
2) Activate check on wallet 2

As a result wallet 2 balance increased with the check amount, but the balance of the wallet 1 stays the same.

Example of different balance for the same address on explorer and api:
https://testnet.explorer.minter.network/address/Mxdee8fc3535274ff90f5343c6db2a80b2e23c29d4
https://minter-node-1.testnet.minter.network/address?address=Mxdee8fc3535274ff90f5343c6db2a80b2e23c29d4

**Comment by shrpne** [comment]
Thank you, it should be fixed already
